#!/bin/bash
# ============================================================================
# AgentSandbox - Nightly Auto-Iteration Pipeline
# Runs every night: analyze → plan → code → test → PR → merge
# Self-evolving: Claude decides what to work on based on current state
# ============================================================================

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOGS_DIR="$PROJECT_DIR/automation/logs/nightly"
DATE=$(date '+%Y-%m-%d')
CLAUDE_BIN="$(which claude)"
FEISHU="$PROJECT_DIR/automation/feishu-notify.sh"
REPO="LURENYUANSHI/agent-sandbox"
LOG="$LOGS_DIR/$DATE.log"

mkdir -p "$LOGS_DIR"

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(timestamp)] $1" >> "$LOG"; echo "[$(timestamp)] $1" >&2; }
notify() { bash "$FEISHU" "$@" >/dev/null 2>&1 || true; }

# ============================================================================
# Step 1: Analyze current state and decide what to do
# ============================================================================
analyze_and_plan() {
    log "Step 1: Analyzing project and planning tonight's work..."

    cd "$PROJECT_DIR"
    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true

    # Collect project state
    local coverage=$(go test ./... -cover -count=1 -timeout 300s 2>&1 | grep -E "^ok|coverage" | grep -v "node_modules")
    local test_result=$(go test ./... -count=1 -timeout 300s 2>&1 | grep -E "^ok|^FAIL")
    local fail_count=$(echo "$test_result" | grep -c "^FAIL" || echo "0")
    local open_issues=$(gh issue list --repo "$REPO" --state open --json number,title --jq '.[] | "#\(.number) \(.title)"' 2>/dev/null)
    local git_log=$(git log --oneline -10)
    local eval_report=$(cat docs/v0.3.0-evaluation.md 2>/dev/null | head -80 || echo "No evaluation report")

    # Let Claude analyze and create a plan
    local plan=$("$CLAUDE_BIN" -p "You are the nightly iteration planner for AgentSandbox (AI Agent Security Sandbox).

Current date: $DATE

## Project State
\`\`\`
$coverage
\`\`\`

Test failures: $fail_count
Open issues: $open_issues
Recent commits:
\`\`\`
$git_log
\`\`\`

Evaluation summary:
\`\`\`
$eval_report
\`\`\`

## Your Task
Decide what to work on tonight. Pick 3-5 high-impact tasks. For each task output EXACTLY this format:

TASK: <one-line description>
TYPE: fix|feat|test|refactor|docs
SCOPE: <package name>
PRIORITY: P0|P1|P2
PROMPT: <detailed prompt for Claude to execute this task, 3-10 sentences>
---

Rules:
- Fix failing tests first (P0)
- Then improve lowest coverage packages
- Then add missing features from evaluation report
- Don't repeat work already done (check git log)
- Be specific in prompts - include file paths, function names, expected behavior
- Each task should be completable in 15-30 minutes by Claude" \
        --dangerously-skip-permissions --model sonnet \
        2>/dev/null)

    echo "$plan" > "$LOGS_DIR/$DATE-plan.txt"
    log "Plan created: $LOGS_DIR/$DATE-plan.txt"
    echo "$plan"
}

# ============================================================================
# Step 2: Execute each task
# ============================================================================
execute_task() {
    local task_num=$1
    local description=$2
    local task_type=$3
    local scope=$4
    local prompt=$5

    log "Task $task_num: [$task_type($scope)] $description"
    notify "phase_start" "Nightly task $task_num" "$description"

    # Create issue
    local issue_url=$(gh issue create --repo "$REPO" \
        --title "$task_type($scope): $description" \
        --body "## Nightly Iteration $DATE - Task $task_num
### Description
$description
### Acceptance Criteria
- [ ] Code compiles
- [ ] All tests pass
- [ ] Committed
---
Auto-generated by nightly pipeline" \
        --label "type::${task_type},priority::p1,agent::claude,automated" 2>/dev/null) || true
    local issue_num=$(echo "$issue_url" | awk -F/ '{print $NF}')

    # Create branch
    cd "$PROJECT_DIR"
    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true
    local branch="feature/nightly-${DATE}-task${task_num}"
    git checkout -b "$branch" 2>/dev/null || { git checkout "$branch" 2>/dev/null; git merge develop --no-edit 2>/dev/null || true; }

    # Execute with Claude
    "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch.
Read CLAUDE.md first.

$prompt

After completing:
1. Run go build ./...
2. Run go test ./... -count=1 -timeout 180s
3. If tests fail, fix them
4. Commit with message: $task_type($scope): $description
DO NOT push or create PRs." \
        --dangerously-skip-permissions --model opus --effort max \
        > "$LOGS_DIR/$DATE-task${task_num}.log" 2>&1 || {
        log "  Task $task_num code failed, attempting recovery..."
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Previous task failed. Check git status, read the error in the log, fix issues, run tests, commit." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/$DATE-task${task_num}-recovery.log" 2>&1 || true
    }

    # Test
    local test_ok="pass"
    go build ./... 2>/dev/null || test_ok="fail_build"
    if [ "$test_ok" = "pass" ]; then
        go test ./... -count=1 -timeout 180s 2>/dev/null || test_ok="fail_test"
    fi
    if [ "$test_ok" != "pass" ]; then
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Tests failing: $test_ok. Fix all issues until go build and go test pass. Commit." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/$DATE-task${task_num}-fix.log" 2>&1 || true
        go build ./... 2>/dev/null && go test ./... -count=1 -timeout 180s 2>/dev/null && test_ok="pass" || true
    fi

    # Push + PR + Merge
    git push -u origin "$branch" 2>/dev/null || git push origin "$branch" 2>/dev/null || true
    local close_line=""
    [ -n "$issue_num" ] && close_line="Closes #$issue_num"
    local pr_url=$(gh pr create --repo "$REPO" --base develop --head "$branch" \
        --title "$task_type($scope): $description" \
        --body "## Nightly $DATE - Task $task_num
$description
$close_line
Test: $test_ok
---
Auto-generated" \
        --label "type::${task_type},agent::claude,automated" 2>/dev/null) || true
    local pr_num=$(echo "$pr_url" | awk -F/ '{print $NF}')

    local merged="false"
    if [ -n "$pr_num" ]; then
        gh pr merge "$pr_num" --repo "$REPO" --squash --delete-branch 2>/dev/null && merged="true" || \
        gh pr merge "$pr_num" --repo "$REPO" --merge --delete-branch 2>/dev/null && merged="true" || true
    fi
    if [ "$merged" != "true" ]; then
        git checkout develop 2>/dev/null
        git merge "$branch" --no-edit 2>/dev/null && git push origin develop 2>/dev/null && merged="true" || true
    fi

    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true

    [ -n "$issue_num" ] && gh issue close "$issue_num" --repo "$REPO" --reason completed 2>/dev/null || true

    log "  Task $task_num: test=$test_ok merged=$merged"
    notify "phase_complete" "Task $task_num done" "$description | test=$test_ok"
}

# ============================================================================
# Step 3: Run full test + report
# ============================================================================
final_report() {
    log "Final: running full test suite..."
    cd "$PROJECT_DIR"
    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true

    local coverage=$(go test ./... -cover -count=1 -timeout 300s 2>&1)
    local pass_count=$(echo "$coverage" | grep -c "^ok" || echo "0")
    local fail_count=$(echo "$coverage" | grep -c "^FAIL" || echo "0")

    echo "$coverage" > "$LOGS_DIR/$DATE-final-tests.txt"

    notify "build_complete" "Nightly $DATE complete" "Tests: $pass_count pass, $fail_count fail"
    log "Nightly complete: $pass_count pass, $fail_count fail"
}

# ============================================================================
# MAIN
# ============================================================================
cd "$PROJECT_DIR"

log "============================================"
log "Nightly Iteration Starting: $DATE"
log "============================================"

notify "build_start" "Nightly $DATE started" "Analyzing project and planning tasks..."

# Step 1: Plan
PLAN=$(analyze_and_plan)

# Step 2: Parse and execute tasks
TASK_NUM=0
CURRENT_DESC=""
CURRENT_TYPE=""
CURRENT_SCOPE=""
CURRENT_PROMPT=""

while IFS= read -r line; do
    case "$line" in
        TASK:*)
            CURRENT_DESC="${line#TASK: }"
            ;;
        TYPE:*)
            CURRENT_TYPE="${line#TYPE: }"
            ;;
        SCOPE:*)
            CURRENT_SCOPE="${line#SCOPE: }"
            ;;
        PRIORITY:*)
            ;;
        PROMPT:*)
            CURRENT_PROMPT="${line#PROMPT: }"
            ;;
        ---*)
            if [ -n "$CURRENT_DESC" ] && [ -n "$CURRENT_PROMPT" ]; then
                TASK_NUM=$((TASK_NUM + 1))
                execute_task "$TASK_NUM" "$CURRENT_DESC" "${CURRENT_TYPE:-feat}" "${CURRENT_SCOPE:-general}" "$CURRENT_PROMPT"
            fi
            CURRENT_DESC=""
            CURRENT_TYPE=""
            CURRENT_SCOPE=""
            CURRENT_PROMPT=""
            ;;
    esac
done <<< "$PLAN"

# Handle last task if no trailing ---
if [ -n "$CURRENT_DESC" ] && [ -n "$CURRENT_PROMPT" ]; then
    TASK_NUM=$((TASK_NUM + 1))
    execute_task "$TASK_NUM" "$CURRENT_DESC" "${CURRENT_TYPE:-feat}" "${CURRENT_SCOPE:-general}" "$CURRENT_PROMPT"
fi

# Step 3: Report
final_report

log "============================================"
log "Nightly $DATE Complete ($TASK_NUM tasks)"
log "============================================"
