#!/bin/bash
# ============================================================================
# AgentSandbox v0.2.0 Iteration Pipeline
# 10 phases: bugfix → auth → ratelimit → dashboard → websocket → config → coverage → cicd → resources → score
# ============================================================================

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PHASES_DIR="$PROJECT_DIR/automation/phases-v2"
LOGS_DIR="$PROJECT_DIR/automation/logs/v2"
PROGRESS_FILE="$PROJECT_DIR/automation/progress-v2.json"
CLAUDE_BIN="$(which claude)"
FEISHU="$PROJECT_DIR/automation/feishu-notify.sh"
REPO="LURENYUANSHI/agent-sandbox"

mkdir -p "$LOGS_DIR"

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(timestamp)] $1" >> "$LOGS_DIR/orchestrator.log"; echo "[$(timestamp)] $1" >&2; }
notify() { bash "$FEISHU" "$@" >/dev/null 2>&1 || true; }

export PD="$PROJECT_DIR"

get_desc() {
    case "$1" in
        phase1-bugfix)     echo "Fix 6 bugs from v0.1.0 audit" ;;
        phase2-auth)       echo "Add JWT authentication to API" ;;
        phase3-ratelimit)  echo "Add rate limiting and input validation" ;;
        phase4-dashboard-api) echo "Implement dashboard stats and activity endpoints" ;;
        phase5-websocket)  echo "Connect WebSocket real-time trace to React" ;;
        phase6-config)     echo "Centralize configuration, replace hardcoded values" ;;
        phase7-coverage)   echo "Increase test coverage policy 80%+ trace 80%+" ;;
        phase8-cicd)       echo "Add GitHub Actions CI/CD pipeline" ;;
        phase9-resource-limits) echo "Enforce resource limits and audit logging" ;;
        phase10-score)     echo "Final evaluation and project scoring" ;;
    esac
}

read_status() {
    python -c "
import json,os
try:
    d=json.load(open(os.path.join(os.environ.get('PD',''),'automation','progress-v2.json')))
    print(d['phases']['$1']['status'])
except: print('pending')
" 2>/dev/null || echo "pending"
}

update_status() {
    python -c "
import json,os
f=os.path.join(os.environ.get('PD',''),'automation','progress-v2.json')
try:
    d=json.load(open(f))
    d['phases']['$1']['$2']=$3
    json.dump(d,open(f,'w'),indent=2)
except: pass
" 2>/dev/null || true
}

run_phase() {
    local phase="$1"
    local desc=$(get_desc "$phase")

    log "=========================================="
    log "PHASE: $phase - $desc"
    log "=========================================="

    update_status "$phase" "status" '"running"'
    update_status "$phase" "start" "\"$(timestamp)\""
    notify "phase_start" "v0.2: $phase" "$desc"

    # 1. Create Issue
    local issue_url
    issue_url=$(gh issue create --repo "$REPO" \
        --title "v0.2: $desc" \
        --body "## v0.2.0 Iteration: $phase
### Description
$desc
### Acceptance Criteria
- [ ] Code compiles
- [ ] All tests pass
- [ ] Committed with descriptive message
---
Auto-generated by v0.2.0 pipeline" \
        --label "type::feature,priority::p1,agent::claude,automated" 2>/dev/null) || true
    local issue_num=$(echo "$issue_url" | awk -F/ '{print $NF}')
    log "  Issue: #$issue_num"
    notify "issue_created" "Issue #$issue_num" "$desc"

    # 2. Branch
    cd "$PROJECT_DIR"
    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true
    local branch="feature/v2-${phase}"
    git checkout -b "$branch" 2>/dev/null || { git checkout "$branch" && git merge develop --no-edit 2>/dev/null || true; }

    # 3. Code
    log "  Coding..."
    "$CLAUDE_BIN" -p "$(cat "$PHASES_DIR/${phase}.md")" \
        --dangerously-skip-permissions --model opus --effort max \
        > "$LOGS_DIR/${phase}-code.log" 2>&1 || {
        log "  Code failed, recovery..."
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Previous coding failed. Read automation/phases-v2/${phase}.md, fix issues, run tests, commit locally. DO NOT push." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/${phase}-recovery.log" 2>&1 || true
    }

    # 4. Test
    log "  Testing..."
    local test_ok="pass"
    if [ -f "go.mod" ]; then
        go build ./... > "$LOGS_DIR/${phase}-test.log" 2>&1 || test_ok="fail_build"
        if [ "$test_ok" = "pass" ]; then
            go test ./... -count=1 -timeout 180s >> "$LOGS_DIR/${phase}-test.log" 2>&1 || test_ok="fail_test"
        fi
    fi
    if [ "$test_ok" != "pass" ]; then
        log "  Tests failed ($test_ok), auto-fixing..."
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Tests failing: $test_ok. Fix all issues. Run go build ./... and go test ./... until pass. Commit locally only." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/${phase}-fix.log" 2>&1 || true
        go build ./... 2>/dev/null && go test ./... -count=1 -timeout 180s 2>/dev/null && test_ok="pass" || true
    fi
    log "  Tests: $test_ok"

    # 5. Push + PR
    git push -u origin "$branch" 2>/dev/null || git push origin "$branch" 2>/dev/null || true
    local close_line=""
    [ -n "$issue_num" ] && close_line="Closes #$issue_num"
    local pr_url
    pr_url=$(gh pr create --repo "$REPO" --base develop --head "$branch" \
        --title "v0.2($phase): $desc" \
        --body "## Summary
$desc
$close_line
---
Auto-generated by v0.2.0 pipeline" \
        --label "type::feature,status::review,agent::claude,automated" 2>/dev/null) || true
    local pr_num=$(echo "$pr_url" | awk -F/ '{print $NF}')
    [ -n "$pr_num" ] && log "  PR: #$pr_num" && notify "pr_created" "PR #$pr_num" "$desc"

    # 6. Merge
    local merged="false"
    if [ -n "$pr_num" ]; then
        gh pr merge "$pr_num" --repo "$REPO" --squash --delete-branch 2>/dev/null && merged="true" || \
        gh pr merge "$pr_num" --repo "$REPO" --merge --delete-branch 2>/dev/null && merged="true" || true
    fi
    if [ "$merged" != "true" ]; then
        # Fallback: local merge
        git checkout develop 2>/dev/null
        git merge "$branch" --no-edit 2>/dev/null && git push origin develop 2>/dev/null && merged="true" || true
    fi
    [ "$merged" = "true" ] && notify "pr_merged" "PR #$pr_num merged" "$desc"

    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true

    # Status
    update_status "$phase" "end" "\"$(timestamp)\""
    if [ "$merged" = "true" ]; then
        update_status "$phase" "status" '"completed"'
        log "COMPLETED: $phase"
        notify "phase_complete" "$phase done" "$desc | Test: $test_ok"
        [ -n "$issue_num" ] && gh issue close "$issue_num" --repo "$REPO" --reason completed 2>/dev/null || true
    else
        update_status "$phase" "status" '"done_no_merge"'
        log "DONE (no merge): $phase"
    fi
}

# ============================================================================
# MAIN
# ============================================================================
cd "$PROJECT_DIR"

log "============================================"
log "AgentSandbox v0.2.0 Pipeline Starting"
log "============================================"

notify "build_start" "v0.2.0 Pipeline Started" "10 phases: bugfix, auth, ratelimit, dashboard, websocket, config, coverage, cicd, resources, score"

# Init progress
cat > "$PROGRESS_FILE" <<'EOF'
{"phases":{"phase1-bugfix":{"status":"pending","start":"","end":""},"phase2-auth":{"status":"pending","start":"","end":""},"phase3-ratelimit":{"status":"pending","start":"","end":""},"phase4-dashboard-api":{"status":"pending","start":"","end":""},"phase5-websocket":{"status":"pending","start":"","end":""},"phase6-config":{"status":"pending","start":"","end":""},"phase7-coverage":{"status":"pending","start":"","end":""},"phase8-cicd":{"status":"pending","start":"","end":""},"phase9-resource-limits":{"status":"pending","start":"","end":""},"phase10-score":{"status":"pending","start":"","end":""}}}
EOF

PHASES=(phase1-bugfix phase2-auth phase3-ratelimit phase4-dashboard-api phase5-websocket phase6-config phase7-coverage phase8-cicd phase9-resource-limits phase10-score)

for phase in "${PHASES[@]}"; do
    status=$(read_status "$phase")
    [ "$status" = "completed" ] && { log "Skip: $phase"; continue; }
    run_phase "$phase"
done

# Release PR
git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true
RELEASE_PR=$(gh pr create --repo "$REPO" --base main --head develop \
    --title "release: AgentSandbox v0.2.0" \
    --body "## v0.2.0 Release
- 6 bugs fixed
- JWT auth, rate limiting, input validation
- Dashboard API, WebSocket integration
- Configurable settings, resource limits, audit logging
- CI/CD pipeline, test coverage improvements
Auto-generated" --label "type::chore" 2>/dev/null) || true
[ -n "$RELEASE_PR" ] && gh pr merge "$RELEASE_PR" --repo "$REPO" --merge 2>/dev/null || true

# Tag
git checkout main 2>/dev/null && git pull origin main 2>/dev/null || true
git tag -a v0.2.0 -m "AgentSandbox v0.2.0" 2>/dev/null && git push origin v0.2.0 2>/dev/null || true
git checkout develop 2>/dev/null

notify "build_complete" "v0.2.0 Pipeline Complete" "All phases done. Release tagged."

log "============================================"
log "v0.2.0 Pipeline Complete"
log "============================================"
