#!/bin/bash
# ============================================================================
# AgentSandbox v0.3.0 Iteration Pipeline
# 10 phases: templates → swagger → rbac → audit → cli-tests → demo → python-sdk → mcp → prometheus → final
# ============================================================================

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PHASES_DIR="$PROJECT_DIR/automation/phases-v3"
LOGS_DIR="$PROJECT_DIR/automation/logs/v3"
PROGRESS_FILE="$PROJECT_DIR/automation/progress-v3.json"
CLAUDE_BIN="$(which claude)"
FEISHU="$PROJECT_DIR/automation/feishu-notify.sh"
REPO="LURENYUANSHI/agent-sandbox"

mkdir -p "$LOGS_DIR"

timestamp() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(timestamp)] $1" >> "$LOGS_DIR/orchestrator.log"; echo "[$(timestamp)] $1" >&2; }
notify() { bash "$FEISHU" "$@" >/dev/null 2>&1 || true; }

export PD="$PROJECT_DIR"

get_desc() {
    case "$1" in
        phase1-templates)      echo "Add GitHub issue/PR templates and contributing guide" ;;
        phase2-swagger)        echo "Add OpenAPI/Swagger API documentation" ;;
        phase3-rbac)           echo "Add role-based access control (admin/operator/viewer)" ;;
        phase4-audit-rotation) echo "Add audit log rotation and improve API coverage" ;;
        phase5-cli-tests)      echo "Add CLI integration tests" ;;
        phase6-demo)           echo "Create interactive demo examples" ;;
        phase7-python-sdk)     echo "Create Python SDK client library" ;;
        phase8-mcp)            echo "Add MCP server for AI agent integration" ;;
        phase9-prometheus)     echo "Add Prometheus metrics endpoint" ;;
        phase10-final)         echo "Final evaluation and v0.3.0 scoring" ;;
    esac
}

read_status() {
    python -c "
import json,os
try:
    d=json.load(open(os.path.join(os.environ.get('PD',''),'automation','progress-v3.json')))
    print(d['phases']['$1']['status'])
except: print('pending')
" 2>/dev/null || echo "pending"
}

update_status() {
    python -c "
import json,os
f=os.path.join(os.environ.get('PD',''),'automation','progress-v3.json')
try:
    d=json.load(open(f))
    d['phases']['$1']['$2']=$3
    json.dump(d,open(f,'w'),indent=2)
except: pass
" 2>/dev/null || true
}

run_phase() {
    local phase="$1"
    local desc=$(get_desc "$phase")

    log "=========================================="
    log "PHASE: $phase - $desc"
    log "=========================================="

    update_status "$phase" "status" '"running"'
    update_status "$phase" "start" "\"$(timestamp)\""
    notify "phase_start" "v0.3: $phase" "$desc"

    # 1. Create Issue
    local issue_url
    issue_url=$(gh issue create --repo "$REPO" \
        --title "v0.3: $desc" \
        --body "## v0.3.0 Iteration: $phase
### Description
$desc
### Acceptance Criteria
- [ ] Code compiles
- [ ] All tests pass
- [ ] Committed with descriptive message
---
Auto-generated by v0.3.0 pipeline" \
        --label "type::feature,priority::p1,agent::claude,automated" 2>/dev/null) || true
    local issue_num=$(echo "$issue_url" | awk -F/ '{print $NF}')
    log "  Issue: #$issue_num"
    notify "issue_created" "Issue #$issue_num" "$desc"

    # 2. Branch
    cd "$PROJECT_DIR"
    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true
    local branch="feature/v3-${phase}"
    git checkout -b "$branch" 2>/dev/null || { git checkout "$branch" && git merge develop --no-edit 2>/dev/null || true; }

    # 3. Code
    log "  Coding..."
    "$CLAUDE_BIN" -p "$(cat "$PHASES_DIR/${phase}.md")" \
        --dangerously-skip-permissions --model opus --effort max \
        > "$LOGS_DIR/${phase}-code.log" 2>&1 || {
        log "  Code failed, recovery..."
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Previous coding failed. Read automation/phases-v3/${phase}.md, fix issues, run tests, commit locally. DO NOT push." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/${phase}-recovery.log" 2>&1 || true
    }

    # 4. Test
    log "  Testing..."
    local test_ok="pass"
    if [ -f "go.mod" ]; then
        go build ./... > "$LOGS_DIR/${phase}-test.log" 2>&1 || test_ok="fail_build"
        if [ "$test_ok" = "pass" ]; then
            go test ./... -count=1 -timeout 180s >> "$LOGS_DIR/${phase}-test.log" 2>&1 || test_ok="fail_test"
        fi
    fi
    if [ "$test_ok" != "pass" ]; then
        log "  Tests failed ($test_ok), auto-fixing..."
        "$CLAUDE_BIN" -p "You are in $PROJECT_DIR on branch $branch. Tests failing: $test_ok. Fix all issues. Run go build ./... and go test ./... until pass. Commit locally only." \
            --dangerously-skip-permissions --model opus --effort max \
            > "$LOGS_DIR/${phase}-fix.log" 2>&1 || true
        go build ./... 2>/dev/null && go test ./... -count=1 -timeout 180s 2>/dev/null && test_ok="pass" || true
    fi
    log "  Tests: $test_ok"

    # 5. Push + PR
    git push -u origin "$branch" 2>/dev/null || git push origin "$branch" 2>/dev/null || true
    local close_line=""
    [ -n "$issue_num" ] && close_line="Closes #$issue_num"
    local pr_url
    pr_url=$(gh pr create --repo "$REPO" --base develop --head "$branch" \
        --title "v0.3($phase): $desc" \
        --body "## Summary
$desc
$close_line
---
Auto-generated by v0.3.0 pipeline" \
        --label "type::feature,status::review,agent::claude,automated" 2>/dev/null) || true
    local pr_num=$(echo "$pr_url" | awk -F/ '{print $NF}')
    [ -n "$pr_num" ] && log "  PR: #$pr_num" && notify "pr_created" "PR #$pr_num" "$desc"

    # 6. Merge
    local merged="false"
    if [ -n "$pr_num" ]; then
        gh pr merge "$pr_num" --repo "$REPO" --squash --delete-branch 2>/dev/null && merged="true" || \
        gh pr merge "$pr_num" --repo "$REPO" --merge --delete-branch 2>/dev/null && merged="true" || true
    fi
    if [ "$merged" != "true" ]; then
        git checkout develop 2>/dev/null
        git merge "$branch" --no-edit 2>/dev/null && git push origin develop 2>/dev/null && merged="true" || true
    fi
    [ "$merged" = "true" ] && notify "pr_merged" "PR #$pr_num merged" "$desc"

    git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true

    # Status
    update_status "$phase" "end" "\"$(timestamp)\""
    if [ "$merged" = "true" ]; then
        update_status "$phase" "status" '"completed"'
        log "COMPLETED: $phase"
        notify "phase_complete" "$phase done" "$desc | Test: $test_ok"
        [ -n "$issue_num" ] && gh issue close "$issue_num" --repo "$REPO" --reason completed 2>/dev/null || true
    else
        update_status "$phase" "status" '"done_no_merge"'
        log "DONE (no merge): $phase"
    fi
}

# ============================================================================
# MAIN
# ============================================================================
cd "$PROJECT_DIR"

log "============================================"
log "AgentSandbox v0.3.0 Pipeline Starting"
log "============================================"

notify "build_start" "v0.3.0 Pipeline Started" "10 phases: templates, swagger, rbac, audit, cli-tests, demo, python-sdk, mcp, prometheus, final"

# Init progress
cat > "$PROGRESS_FILE" <<'EOF'
{"phases":{"phase1-templates":{"status":"pending","start":"","end":""},"phase2-swagger":{"status":"pending","start":"","end":""},"phase3-rbac":{"status":"pending","start":"","end":""},"phase4-audit-rotation":{"status":"pending","start":"","end":""},"phase5-cli-tests":{"status":"pending","start":"","end":""},"phase6-demo":{"status":"pending","start":"","end":""},"phase7-python-sdk":{"status":"pending","start":"","end":""},"phase8-mcp":{"status":"pending","start":"","end":""},"phase9-prometheus":{"status":"pending","start":"","end":""},"phase10-final":{"status":"pending","start":"","end":""}}}
EOF

PHASES=(phase1-templates phase2-swagger phase3-rbac phase4-audit-rotation phase5-cli-tests phase6-demo phase7-python-sdk phase8-mcp phase9-prometheus phase10-final)

for phase in "${PHASES[@]}"; do
    status=$(read_status "$phase")
    [ "$status" = "completed" ] && { log "Skip: $phase"; continue; }
    run_phase "$phase"
done

# Release PR
git checkout develop 2>/dev/null && git pull origin develop 2>/dev/null || true
RELEASE_PR=$(gh pr create --repo "$REPO" --base main --head develop \
    --title "release: AgentSandbox v0.3.0" \
    --body "## v0.3.0 Release
- GitHub issue/PR templates, contributing guide
- OpenAPI/Swagger API docs
- RBAC (admin/operator/viewer)
- Audit log rotation
- CLI tests, interactive demos
- Python SDK, MCP server, Prometheus metrics
Auto-generated" --label "type::chore" 2>/dev/null) || true
[ -n "$RELEASE_PR" ] && gh pr merge "$RELEASE_PR" --repo "$REPO" --merge 2>/dev/null || true

# Tag
git checkout main 2>/dev/null && git pull origin main 2>/dev/null || true
git tag -a v0.3.0 -m "AgentSandbox v0.3.0" 2>/dev/null && git push origin v0.3.0 2>/dev/null || true
git checkout develop 2>/dev/null

notify "build_complete" "v0.3.0 Pipeline Complete" "All phases done. Release tagged."

log "============================================"
log "v0.3.0 Pipeline Complete"
log "============================================"
