#!/bin/bash
# ============================================================================
# AgentSandbox - Overnight Autonomous Development Pipeline
# Runs 9 phases of development using Claude Code in non-interactive mode
# Integrates: GitHub (Issues, PRs, branches) + Feishu notifications
# Expected duration: ~8 hours (00:00 - 08:00)
# ============================================================================

set -euo pipefail

PROJECT_DIR="/c/Users/Administrator/ai-sandbox"
PHASES_DIR="$PROJECT_DIR/automation/phases"
LOGS_DIR="$PROJECT_DIR/automation/logs"
PROGRESS_FILE="$PROJECT_DIR/automation/progress.json"
CLAUDE_BIN="/c/Users/Administrator/.local/bin/claude"
FEISHU="$PROJECT_DIR/automation/feishu-notify.sh"
REPO="LURENYUANSHI/agent-sandbox"

# Ensure logs directory exists
mkdir -p "$LOGS_DIR"

# Timestamp helper
timestamp() {
    date '+%Y-%m-%d %H:%M:%S'
}

# Log helper
log() {
    echo "[$(timestamp)] $1" | tee -a "$LOGS_DIR/orchestrator.log"
}

# ---- Feishu notification (safe - never fail the pipeline) ----
notify() {
    bash "$FEISHU" "$@" 2>/dev/null || true
}

# ---- GitHub helpers ----

# Create an issue for a phase and return issue number
create_phase_issue() {
    local phase_name=$1
    local phase_desc=$2

    local issue_num=$(gh issue create \
        --repo "$REPO" \
        --title "feat: $phase_desc" \
        --body "$(cat <<EOF
## Phase: $phase_name

**Auto-generated by AgentSandbox Overnight Pipeline**

### Description
$phase_desc

### Acceptance Criteria
- [ ] All code for this phase is written
- [ ] All tests pass
- [ ] Code compiles without errors
- [ ] Git commit with descriptive message

### Phase Prompt
See \`automation/phases/${phase_name}.md\` for full details.
EOF
)" \
        --label "automated,overnight-build" 2>/dev/null | grep -oP '\d+$' || echo "")

    if [ -n "$issue_num" ]; then
        log "Created issue #$issue_num for $phase_name"
        notify "issue_created" "Issue #$issue_num: $phase_desc" "[View Issue](https://github.com/$REPO/issues/$issue_num)"
        echo "$issue_num"
    else
        log "WARN: Failed to create issue for $phase_name"
        echo ""
    fi
}

# Create a feature branch for a phase
create_phase_branch() {
    local phase_name=$1
    local branch="feature/$phase_name"
    git checkout develop 2>/dev/null
    git pull origin develop 2>/dev/null || true
    git checkout -b "$branch" 2>/dev/null || git checkout "$branch" 2>/dev/null
    echo "$branch"
}

# Create PR from feature branch to develop
create_phase_pr() {
    local phase_name=$1
    local phase_desc=$2
    local issue_num=$3
    local branch="feature/$phase_name"

    git push -u origin "$branch" 2>/dev/null || true

    local close_text=""
    if [ -n "$issue_num" ]; then
        close_text="Closes #$issue_num"
    fi

    local pr_url=$(gh pr create \
        --repo "$REPO" \
        --base develop \
        --head "$branch" \
        --title "feat: $phase_desc" \
        --body "$(cat <<EOF
## Summary
$phase_desc

Auto-generated by AgentSandbox Overnight Pipeline.

$close_text

## Changes
See commits in this PR for details.

## Test Plan
- All unit tests pass (\`go test ./...\`)
- Code compiles (\`go build ./...\`)
- go vet passes

---
🤖 Generated by AgentSandbox Autonomous Pipeline
EOF
)" 2>/dev/null || echo "")

    if [ -n "$pr_url" ]; then
        local pr_num=$(echo "$pr_url" | grep -oP '\d+$' || echo "")
        log "Created PR $pr_url for $phase_name"
        notify "pr_created" "PR #$pr_num: $phase_desc" "[View PR]($pr_url)"
        echo "$pr_url"
    else
        log "WARN: Failed to create PR for $phase_name"
        echo ""
    fi
}

# Merge PR and clean up
merge_phase_pr() {
    local pr_url=$1
    local branch=$2

    if [ -n "$pr_url" ]; then
        gh pr merge "$pr_url" --squash --delete-branch --repo "$REPO" 2>/dev/null || \
        gh pr merge "$pr_url" --merge --delete-branch --repo "$REPO" 2>/dev/null || true
        log "Merged PR: $pr_url"
    fi

    git checkout develop 2>/dev/null
    git pull origin develop 2>/dev/null || true
}

# ---- Phase descriptions ----
declare -A PHASE_DESC
PHASE_DESC=(
    ["phase1-init"]="Initialize project skeleton with Go, React, Docker"
    ["phase2-types"]="Define core types, interfaces, and action model"
    ["phase3-policy"]="Implement policy engine with YAML parsing and glob matching"
    ["phase4-trace"]="Implement trace recording, SQLite storage, and replay"
    ["phase5-sandbox"]="Implement sandbox runtime with filesystem/network/process isolation"
    ["phase6-cli-api"]="Implement CLI with cobra and REST API with gin"
    ["phase7-web"]="Implement React dashboard with trace viewer and replay"
    ["phase8-integration"]="Add integration tests and Docker multi-stage build"
    ["phase9-polish"]="Documentation, evaluation report, and v0.1.0 release"
)

# Initialize progress tracking
init_progress() {
    cat > "$PROGRESS_FILE" << 'PROGRESS_EOF'
{
    "start_time": "",
    "phases": {
        "phase1-init": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase2-types": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase3-policy": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase4-trace": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase5-sandbox": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase6-cli-api": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase7-web": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase8-integration": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""},
        "phase9-polish": {"status": "pending", "start": "", "end": "", "exit_code": -1, "issue": "", "pr": "", "branch": ""}
    },
    "end_time": "",
    "overall_status": "running"
}
PROGRESS_EOF
    sed -i "s/\"start_time\": \"\"/\"start_time\": \"$(timestamp)\"/" "$PROGRESS_FILE"
}

# Update phase status in progress file
update_phase() {
    local phase=$1
    local field=$2
    local value=$3
    python -c "
import json
with open('$PROGRESS_FILE', 'r') as f:
    data = json.load(f)
data['phases']['$phase']['$field'] = $value
with open('$PROGRESS_FILE', 'w') as f:
    json.dump(data, f, indent=2)
"
}

# ---- Run a single phase (full workflow: issue -> branch -> code -> PR -> merge) ----
run_phase() {
    local phase_name=$1
    local phase_file="$PHASES_DIR/${phase_name}.md"
    local phase_log="$LOGS_DIR/${phase_name}.log"
    local desc="${PHASE_DESC[$phase_name]}"

    if [ ! -f "$phase_file" ]; then
        log "ERROR: Phase file not found: $phase_file"
        return 1
    fi

    log "=========================================="
    log "Starting: $phase_name - $desc"
    log "=========================================="

    # 1. Create GitHub Issue
    local issue_num=$(create_phase_issue "$phase_name" "$desc")
    update_phase "$phase_name" "issue" "\"$issue_num\""

    # 2. Create feature branch
    local branch=$(create_phase_branch "$phase_name")
    update_phase "$phase_name" "branch" "\"$branch\""

    # 3. Update status
    update_phase "$phase_name" "status" '"running"'
    update_phase "$phase_name" "start" "\"$(timestamp)\""
    notify "phase_start" "Phase Started: $phase_name" "$desc"

    # 4. Read the phase prompt
    local prompt
    prompt=$(cat "$phase_file")

    # 5. Run Claude Code in non-interactive mode
    local exit_code=0
    cd "$PROJECT_DIR"
    "$CLAUDE_BIN" -p "$prompt" \
        --dangerously-skip-permissions \
        --model opus \
        --effort max \
        --verbose \
        > "$phase_log" 2>&1 || exit_code=$?

    update_phase "$phase_name" "end" "\"$(timestamp)\""
    update_phase "$phase_name" "exit_code" "$exit_code"

    local start_ts=$(python -c "
import json
with open('$PROGRESS_FILE') as f:
    d = json.load(f)
print(d['phases']['$phase_name']['start'])
" 2>/dev/null)
    local end_ts=$(timestamp)

    if [ $exit_code -eq 0 ]; then
        update_phase "$phase_name" "status" '"completed"'
        log "COMPLETED: $phase_name"
        notify "phase_complete" "Phase Completed: $phase_name" "$desc\\n\\nStarted: $start_ts\\nEnded: $end_ts"

        # 6. Push and create PR
        local pr_url=$(create_phase_pr "$phase_name" "$desc" "$issue_num")
        update_phase "$phase_name" "pr" "\"$pr_url\""

        # 7. Auto-merge PR into develop
        merge_phase_pr "$pr_url" "$branch"
    else
        update_phase "$phase_name" "status" '"failed"'
        log "FAILED: $phase_name (exit code: $exit_code)"
        notify "phase_failed" "Phase Failed: $phase_name" "Exit code: $exit_code\\n\\nAttempting recovery..."

        # Attempt recovery
        log "Attempting recovery for $phase_name..."
        local recovery_prompt="You are working on /c/Users/Administrator/ai-sandbox on branch feature/$phase_name. The previous phase ($phase_name) failed. Read the CLAUDE.md and check git log and git status. Read automation/phases/${phase_name}.md. Fix any issues, complete remaining work, run tests, commit when done."

        "$CLAUDE_BIN" -p "$recovery_prompt" \
            --dangerously-skip-permissions \
            --model opus \
            --effort max \
            > "$LOGS_DIR/${phase_name}-recovery.log" 2>&1 || true

        if (cd "$PROJECT_DIR" && go build ./... 2>/dev/null); then
            update_phase "$phase_name" "status" '"recovered"'
            log "RECOVERED: $phase_name"
            notify "phase_recovered" "Phase Recovered: $phase_name" "Recovery succeeded after initial failure"

            local pr_url=$(create_phase_pr "$phase_name" "$desc (recovered)" "$issue_num")
            update_phase "$phase_name" "pr" "\"$pr_url\""
            merge_phase_pr "$pr_url" "$branch"
        else
            log "RECOVERY FAILED: $phase_name - continuing"
            notify "phase_failed" "Recovery Failed: $phase_name" "Could not recover. Continuing to next phase."
            # Still try to go back to develop for next phase
            git checkout develop 2>/dev/null || true
        fi
    fi

    return 0
}

# ============================================================================
# Main execution
# ============================================================================

cd "$PROJECT_DIR"

log "============================================"
log "AgentSandbox Overnight Build Starting"
log "Project: $PROJECT_DIR"
log "Repo: $REPO"
log "============================================"

# Create labels on the repo
gh label create "automated" --color "0e8a16" --description "Auto-generated by pipeline" --repo "$REPO" 2>/dev/null || true
gh label create "overnight-build" --color "1d76db" --description "Part of overnight build" --repo "$REPO" 2>/dev/null || true

notify "build_start" "Overnight Build Started" "Starting 9-phase autonomous development pipeline.\\n\\nRepo: github.com/$REPO\\nPhases: 9\\nEstimated duration: ~8 hours"

init_progress

# Phase list in order
PHASES=(
    "phase1-init"
    "phase2-types"
    "phase3-policy"
    "phase4-trace"
    "phase5-sandbox"
    "phase6-cli-api"
    "phase7-web"
    "phase8-integration"
    "phase9-polish"
)

# Check if we should resume from a specific phase
RESUME_FROM=""
if [ -f "$PROGRESS_FILE" ]; then
    for phase in "${PHASES[@]}"; do
        status=$(python -c "
import json
with open('$PROGRESS_FILE') as f:
    data = json.load(f)
print(data['phases']['$phase']['status'])
" 2>/dev/null || echo "pending")

        if [ "$status" = "pending" ] || [ "$status" = "failed" ]; then
            RESUME_FROM="$phase"
            break
        fi
    done
fi

# Run all phases
started=false
for phase in "${PHASES[@]}"; do
    if [ -n "$RESUME_FROM" ] && [ "$started" = false ]; then
        if [ "$phase" != "$RESUME_FROM" ]; then
            log "Skipping already completed: $phase"
            continue
        fi
        started=true
    fi

    run_phase "$phase"
done

# ---- Final: merge develop into main ----
log "Merging develop into main..."
git checkout main 2>/dev/null
git pull origin main 2>/dev/null || true
git merge develop --no-edit 2>/dev/null || true
git push origin main 2>/dev/null || true
git checkout develop 2>/dev/null

# ---- Generate summary ----
python -c "
import json
with open('$PROGRESS_FILE', 'r') as f:
    data = json.load(f)
data['end_time'] = '$(timestamp)'
phases = data['phases']
completed = [k for k, v in phases.items() if v['status'] in ('completed', 'recovered')]
failed = [k for k, v in phases.items() if v['status'] == 'failed']
data['overall_status'] = 'completed' if not failed else 'completed_with_errors'
data['summary'] = {
    'completed': len(completed),
    'failed': len(failed),
    'total': len(phases),
    'completed_phases': completed,
    'failed_phases': failed
}
with open('$PROGRESS_FILE', 'w') as f:
    json.dump(data, f, indent=2)
"

# Send final notification
COMPLETED=$(python -c "import json; d=json.load(open('$PROGRESS_FILE')); print(d['summary']['completed'])" 2>/dev/null)
FAILED=$(python -c "import json; d=json.load(open('$PROGRESS_FILE')); print(d['summary']['failed'])" 2>/dev/null)

notify "build_complete" "Overnight Build Complete" "**Results:** $COMPLETED/9 phases completed, $FAILED failed\\n\\n[View Repo](https://github.com/$REPO)\\n\\nCheck \`automation/progress.json\` for full details."

log "============================================"
log "AgentSandbox Overnight Build Complete"
log "Completed: $COMPLETED/9, Failed: $FAILED"
log "Progress: $PROGRESS_FILE"
log "Logs: $LOGS_DIR/"
log "============================================"
